[theme]
primaryColor = "#4285F4"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#1E1E1E"
textColor = "#FFFFFF"

[server]
enableStaticServing = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[ui]
hideTopBar = true

[client]
showSidebarNavigation = false
toolbarMode = "minimal" 